# Generated by Django 4.1.7 on 2023-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='sin_foto.png', upload_to=''),
        ),
    ]
