# Generated by Django 4.1.7 on 2023-04-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0007_alter_profile_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='static/img/default.jpg'),
        ),
    ]
