# Generated by Django 4.1.7 on 2023-04-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0009_alter_profile_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='year_of_opening',
            new_name='estreno',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='musical',
        ),
    ]
