# Generated by Django 4.1.7 on 2023-04-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0010_rename_year_of_opening_post_estreno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='leading_actor',
            new_name='actor_principal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='main_song',
            new_name='cancion_principal',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='song_duration',
            new_name='duracion',
        ),
    ]
