# Generated by Django 4.1.7 on 2023-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0013_post_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
    ]
