# Generated by Django 4.1.7 on 2023-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicales', '0015_post_creado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.CharField(default='es genial', max_length=2000),
            preserve_default=False,
        ),
    ]
